#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/server-filesystem/dist/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/server-filesystem/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules:/mnt/c/Vercel/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/server-filesystem/dist/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/server-filesystem/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules:/mnt/c/Vercel/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js" "$@"
else
  exec node  "$basedir/../.pnpm/@modelcontextprotocol+serve_013a63ca059848fb0d4d2cbca875150c/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js" "$@"
fi
