// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[...slug]" | "/about" | "/blog" | "/blog/[slug]" | "/book" | "/brutus" | "/case-studies" | "/case-studies/ai-outreach-plexus" | "/case-studies/soul-aligned-outreach" | "/changelog" | "/changelog/[slug]" | "/contact" | "/enterprise" | "/enterprise/[slug]" | "/faces" | "/faq" | "/help" | "/intelligence" | "/lgbtq-discount" | "/pricing" | "/privacy-policy" | "/products" | "/products/cadence" | "/services" | "/solutions" | "/solutions/a-la-carte" | "/solutions/automation-skyway" | "/solutions/chatbots" | "/solutions/consensus-engine" | "/solutions/essentials" | "/solutions/flowstack" | "/solutions/redbridging" | "/terms" | "/test-analytics" | "/testimonials"
type AppRouteHandlerRoutes = "/api/brutus" | "/api/brutus/fs" | "/api/brutus/openai" | "/api/brutus/vision" | "/api/claude" | "/api/claude/batch" | "/api/dev-coder" | "/api/intelligence" | "/api/intelligence/fs" | "/api/intelligence/openai" | "/api/intelligence/vision" | "/api/search/internal" | "/api/tts" | "/blog/rss.xml" | "/changelog/rss.xml"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/case-studies" | "/case-studies/[[...path]]"
type RewriteRoutes = "/calendar" | "/calendar/"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[...slug]": { "slug": string[]; }
  "/about": {}
  "/api/brutus": {}
  "/api/brutus/fs": {}
  "/api/brutus/openai": {}
  "/api/brutus/vision": {}
  "/api/claude": {}
  "/api/claude/batch": {}
  "/api/dev-coder": {}
  "/api/intelligence": {}
  "/api/intelligence/fs": {}
  "/api/intelligence/openai": {}
  "/api/intelligence/vision": {}
  "/api/search/internal": {}
  "/api/tts": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/rss.xml": {}
  "/book": {}
  "/brutus": {}
  "/calendar": {}
  "/calendar/": {}
  "/case-studies": {}
  "/case-studies/[[...path]]": { "path"?: string[]; }
  "/case-studies/ai-outreach-plexus": {}
  "/case-studies/soul-aligned-outreach": {}
  "/changelog": {}
  "/changelog/[slug]": { "slug": string; }
  "/changelog/rss.xml": {}
  "/contact": {}
  "/enterprise": {}
  "/enterprise/[slug]": { "slug": string; }
  "/faces": {}
  "/faq": {}
  "/help": {}
  "/intelligence": {}
  "/lgbtq-discount": {}
  "/pricing": {}
  "/privacy-policy": {}
  "/products": {}
  "/products/cadence": {}
  "/services": {}
  "/solutions": {}
  "/solutions/a-la-carte": {}
  "/solutions/automation-skyway": {}
  "/solutions/chatbots": {}
  "/solutions/consensus-engine": {}
  "/solutions/essentials": {}
  "/solutions/flowstack": {}
  "/solutions/redbridging": {}
  "/terms": {}
  "/test-analytics": {}
  "/testimonials": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
