// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../src/app/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/brutus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brutus">> = Specific
  const handler = {} as typeof import("../../src/app/brutus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/case-studies/ai-outreach-plexus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies/ai-outreach-plexus">> = Specific
  const handler = {} as typeof import("../../src/app/case-studies/ai-outreach-plexus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../src/app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/case-studies/soul-aligned-outreach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies/soul-aligned-outreach">> = Specific
  const handler = {} as typeof import("../../src/app/case-studies/soul-aligned-outreach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/changelog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/changelog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../src/app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/enterprise/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/enterprise/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise">> = Specific
  const handler = {} as typeof import("../../src/app/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faces">> = Specific
  const handler = {} as typeof import("../../src/app/faces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lgbtq-discount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lgbtq-discount">> = Specific
  const handler = {} as typeof import("../../src/app/lgbtq-discount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/cadence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/cadence">> = Specific
  const handler = {} as typeof import("../../src/app/products/cadence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/a-la-carte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/a-la-carte">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/a-la-carte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/automation-skyway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/automation-skyway">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/automation-skyway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/chatbots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/chatbots">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/chatbots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/consensus-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/consensus-engine">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/consensus-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/essentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/essentials">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/essentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/flowstack/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/flowstack">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/flowstack/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/redbridging/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/redbridging">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/redbridging/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/test-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brutus/fs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brutus/fs">> = Specific
  const handler = {} as typeof import("../../src/app/api/brutus/fs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brutus/openai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brutus/openai">> = Specific
  const handler = {} as typeof import("../../src/app/api/brutus/openai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brutus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brutus">> = Specific
  const handler = {} as typeof import("../../src/app/api/brutus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brutus/vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brutus/vision">> = Specific
  const handler = {} as typeof import("../../src/app/api/brutus/vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/claude/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claude/batch">> = Specific
  const handler = {} as typeof import("../../src/app/api/claude/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/claude/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claude">> = Specific
  const handler = {} as typeof import("../../src/app/api/claude/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-coder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-coder">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-coder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intelligence/fs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence/fs">> = Specific
  const handler = {} as typeof import("../../src/app/api/intelligence/fs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intelligence/openai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence/openai">> = Specific
  const handler = {} as typeof import("../../src/app/api/intelligence/openai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intelligence/vision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence/vision">> = Specific
  const handler = {} as typeof import("../../src/app/api/intelligence/vision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/internal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search/internal">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/internal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/blog/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/blog/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/changelog/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/changelog/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/changelog/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
