#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules/@workflow/cli/bin/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules/@workflow/cli/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules/@workflow/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules:/mnt/c/Vercel/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules/@workflow/cli/bin/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules/@workflow/cli/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules/@workflow/node_modules:/mnt/c/Vercel/node_modules/.pnpm/@workflow+cli@4.0.1-beta.22_ab558e5d272ed6312cd24969af99eed6/node_modules:/mnt/c/Vercel/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../@workflow/cli/bin/run.js" "$@"
else
  exec node  "$basedir/../../../@workflow/cli/bin/run.js" "$@"
fi
